name: task_flow
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Core utilities
  uuid: ^4.0.0
  http: ^1.2.0
  intl: ^0.19.0
  path_provider: ^2.1.4
  file_picker: ^8.1.2

  # UI & Design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  animated_splash_screen: ^1.3.0

  # Storage & Security
  flutter_secure_storage: ^9.0.0

  # Links & Preview
  url_launcher: ^6.3.0
  flutter_link_previewer: ^3.2.0

  # State Management
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1

  # Notifications
  flutter_local_notifications: ^19.5.0
  flutter_local_notifications_windows: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/logo.svg
    - lib/assets/icons/